/* auto-generated by NAPI-RS */
/* eslint-disable */

/** Rust-backed local index manager with optional auto-refresh polling. */
export declare class IndexManager {
  constructor(projectId: string, projectKey: string, baseUrl?: string | null)
  loadIndex(indexName: string, options?: LoadIndexOptions | null): Promise<IndexInfo>
  unloadIndex(indexName: string): Promise<void>
  hasIndex(indexName: string): Promise<boolean>
  query(indexName: string, query: string, queryEmbedding: Array<number>, topK?: number, alpha?: number, filter?: object): Promise<SearchResult>
  queryText(indexName: string, query: string, topK?: number, alpha?: number, filter?: object): Promise<SearchResult>
  loadQueryModel(indexName: string): Promise<void>
  refreshIndex(indexName: string): Promise<RefreshResult>
  getIndexInfo(indexName: string): Promise<IndexInfo>
}
export type JsIndexManager = IndexManager

/** Rust-backed cloud orchestration client for index mutations and metadata operations. */
export declare class ManageClient {
  constructor(projectId: string, projectKey: string, baseUrl?: string | null)
  createIndex(name: string, docs: Array<DocumentInfo>, modelId: string, onProgress?: (progress: JobProgress) => void): Promise<MutationResult>
  addDocs(name: string, docs: Array<DocumentInfo>, options?: MutationOptions | null, onProgress?: (progress: JobProgress) => void): Promise<MutationResult>
  deleteDocs(name: string, docIds: Array<string>, onProgress?: (progress: JobProgress) => void): Promise<MutationResult>
  getJobStatus(jobId: string): Promise<JobStatusResponse>
  getIndex(name: string): Promise<IndexInfo>
  listIndexes(): Promise<Array<IndexInfo>>
  deleteIndex(name: string): Promise<boolean>
  getDocs(name: string, options?: GetDocumentsOptions | null): Promise<Array<DocumentInfo>>
}
export type JsManageClient = ManageClient

/** Default REST endpoint for Moss Cloud operations. */
export const CLOUD_API_MANAGE_URL: string

/** Document payload that can be indexed and later retrieved. */
export interface DocumentInfo {
  /** Unique identifier within the index. */
  id: string
  /** Canonical text content used for embedding generation. */
  text: string
  /** Optional metadata map persisted alongside the document. */
  metadata?: Record<string, string>
  /** Optional precomputed embedding vector (f64 for JS compatibility). */
  embedding?: Array<number>
}

/** Optional filters when retrieving documents from an index. */
export interface GetDocumentsOptions {
  /** List of document IDs to fetch; omitted returns all documents. */
  docIds?: Array<string>
}

/** Information about a persisted index including status and model metadata. */
export interface IndexInfo {
  /** Unique identifier of the index. */
  id: string
  /** Human-readable index name. */
  name: string
  /** Index build or schema version string. */
  version?: string
  /** Current lifecycle status of the index build. */
  status: IndexStatus
  /** Number of documents stored in the index. */
  docCount: number
  /** RFC 3339 timestamp indicating when the index was created. */
  createdAt?: string
  /** RFC 3339 timestamp indicating the last update time. */
  updatedAt?: string
  /** Embedding model details bound to the index. */
  model: ModelRef
}

/** Lifecycle status for background index creation processes. */
export declare const enum IndexStatus {
  NotStarted = 'NotStarted',
  Building = 'Building',
  Ready = 'Ready',
  Failed = 'Failed'
}

/** Job phase for async cloud operations. */
export declare const enum JobPhase {
  Downloading = 'downloading',
  Deserializing = 'deserializing',
  GeneratingEmbeddings = 'generating_embeddings',
  BuildingIndex = 'building_index',
  Uploading = 'uploading',
  Cleanup = 'cleanup'
}

/** Progress update for async cloud operations. */
export interface JobProgress {
  jobId: string
  status: JobStatus
  progress: number
  currentPhase?: JobPhase
}

/** Job status for async cloud operations. */
export declare const enum JobStatus {
  PendingUpload = 'pending_upload',
  Uploading = 'uploading',
  Building = 'building',
  Completed = 'completed',
  Failed = 'failed'
}

/** Status payload for a long-running async job. */
export interface JobStatusResponse {
  jobId: string
  status: JobStatus
  progress: number
  currentPhase?: JobPhase
  error?: string
  createdAt: string
  updatedAt: string
  completedAt?: string
}

/** Options for loading an index with auto-refresh configuration. */
export interface LoadIndexOptions {
  /** Enable auto-refresh polling for this index. */
  autoRefresh?: boolean
  /** Polling interval in seconds (default: 600 / 10 minutes). */
  pollingIntervalInSeconds?: number
  /** Optional filesystem path for caching index data to disk. */
  cachePath?: string
}

/** Public CDN endpoint for downloading Moss embedding models locally. */
export const MODEL_DOWNLOAD_URL: string

/** Reference to the embedding model powering a Moss index. */
export interface ModelRef {
  /** Model identifier string. */
  id: string
  /** Semantic version or build identifier of the model. */
  version?: string
}

/** Options for async mutation operations. */
export interface MutationOptions {
  upsert?: boolean
}

/** Completed result from an async mutation operation. */
export interface MutationResult {
  jobId: string
  indexName: string
  docCount: number
}

/** Options for query operations. */
export interface QueryOptions {
  /** Caller-provided embedding vector. When supplied, skips embedding generation. */
  embedding?: Array<number>
  /** Number of top results to return. */
  topK?: number
  /** Weight for hybrid search fusion (0.0 to 1.0). Default 0.8. */
  alpha?: number
  /** Optional metadata filter for narrowing results. */
  filter?: any
}

/** Document returned from a query with similarity metadata. */
export interface QueryResultDocumentInfo {
  /** Document identifier. */
  id: string
  /** Original document text. */
  text: string
  /** Optional metadata associated with the document. */
  metadata?: Record<string, string>
  /** Similarity score between 0 and 1 (higher is more relevant). */
  score: number
}

/** Result of an index refresh operation. */
export interface RefreshResult {
  /** Name of the index that was refreshed. */
  indexName: string
  /** Timestamp before the refresh operation. */
  previousUpdatedAt: string
  /** Timestamp after the refresh operation. */
  newUpdatedAt: string
  /** Whether the index was actually updated (true if cloud had newer version). */
  wasUpdated: boolean
}

/** Semantic version identifier for the Moss JavaScript core bindings. */
export const SDK_VERSION_NUMBER: string

/** Result payload returned by a semantic query operation. */
export interface SearchResult {
  /** Matching documents ordered by similarity. */
  docs: Array<QueryResultDocumentInfo>
  /** Original query string for reference. */
  query: string
  /** Optional index name when available. */
  indexName?: string
  /** Optional execution time in milliseconds. */
  timeTakenInMs?: number
}

