// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

let nativeBinding = null
const loadErrors = []

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./js-binding.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@moss-dev/moss-core-win32-x64-msvc')
        const bindingPackageVersion = require('@moss-dev/moss-core-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.8.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.8.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    if (process.arch === 'arm64') {
      try {
        return require('./js-binding.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@moss-dev/moss-core-darwin-arm64')
        const bindingPackageVersion = require('@moss-dev/moss-core-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.8.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.8.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      try {
        return require('./js-binding.linux-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@moss-dev/moss-core-linux-x64-gnu')
        const bindingPackageVersion = require('@moss-dev/moss-core-linux-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.8.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.8.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./js-binding.linux-arm64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@moss-dev/moss-core-linux-arm64-gnu')
        const bindingPackageVersion = require('@moss-dev/moss-core-linux-arm64-gnu/package.json').version
        if (bindingPackageVersion !== '0.8.7' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.8.7 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.IndexManager = nativeBinding.IndexManager
module.exports.JsIndexManager = nativeBinding.JsIndexManager
module.exports.ManageClient = nativeBinding.ManageClient
module.exports.JsManageClient = nativeBinding.JsManageClient
module.exports.CLOUD_API_MANAGE_URL = nativeBinding.CLOUD_API_MANAGE_URL
module.exports.IndexStatus = nativeBinding.IndexStatus
module.exports.JsIndexStatus = nativeBinding.JsIndexStatus
module.exports.JobPhase = nativeBinding.JobPhase
module.exports.JsJobPhase = nativeBinding.JsJobPhase
module.exports.JobStatus = nativeBinding.JobStatus
module.exports.JsJobStatus = nativeBinding.JsJobStatus
module.exports.MODEL_DOWNLOAD_URL = nativeBinding.MODEL_DOWNLOAD_URL
module.exports.SDK_VERSION_NUMBER = nativeBinding.SDK_VERSION_NUMBER
